// levels.js

const levels = [
    {
        // Level 1
        gridStatic: [
            [2, 2, 1, 1, 1, 2, 2, 2, 2],
            [2, 2, 1, 3, 1, 2, 2, 2, 2],
            [2, 2, 1, 0, 1, 1, 1, 1, 2],
            [1, 1, 1, 0, 0, 0, 3, 1, 2],
            [1, 3, 0, 0, 0, 1, 1, 1, 2],
            [1, 1, 1, 1, 0, 1, 2, 2, 2],
            [2, 2, 2, 1, 3, 1, 2, 2, 2],
            [2, 2, 2, 1, 1, 1, 2, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 4, 0, 4, 0, 0, 0],
            [0, 0, 0, 4, 5, 0, 0, 0, 0],
            [0, 0, 0, 0, 4, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "down",
            "up",
            "left",
            "left",
            "right",
            "up",
            "up",
            "down",
            "right",
            "right"
        ]
    },
    {
        // Level 2
        gridStatic: [
            [1, 1, 1, 1, 1, 2, 2, 2, 2],
            [1, 0, 0, 0, 1, 2, 2, 2, 2],
            [1, 0, 0, 0, 1, 2, 1, 1, 1],
            [1, 0, 0, 0, 1, 2, 1, 3, 1],
            [1, 1, 1, 0, 1, 1, 1, 3, 1],
            [2, 1, 1, 0, 0, 0, 0, 3, 1],
            [2, 1, 0, 0, 0, 1, 0, 0, 1],
            [2, 1, 0, 0, 0, 1, 1, 1, 1],
            [2, 1, 1, 1, 1, 1, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 5, 0, 0, 0, 0, 0],
            [0, 0, 4, 4, 0, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "down",
            "down",
            "down",
            "down",
            "right",
            "down",
            "down",
            "left",
            "left",
            "up",
            "right",
            "down",
            "right",
            "up",
            "left",
            "up",
            "up",
            "up",
            "up",
            "up",
            "left",
            "left",
            "down",
            "right",
            "up",
            "right",
            "down",
            "down",
            "down",
            "down",
            "right",
            "right",
            "right",
            "down",
            "right",
            "up",
            "up",
            "down",
            "left",
            "left",
            "left",
            "down",
            "down",
            "left",
            "left",
            "up",
            "right",
            "down",
            "right",
            "up",
            "left",
            "up",
            "up",
            "up",
            "up",
            "left",
            "left",
            "down",
            "right",
            "up",
            "right",
            "down",
            "down",
            "down",
            "right",
            "right",
            "right",
            "down",
            "right",
            "up",
            "left",
            "left",
            "left",
            "down",
            "down",
            "left",
            "left",
            "up",
            "right",
            "down",
            "right",
            "up",
            "left",
            "up",
            "right",
            "right",
            "right"
        ]
    },
    {
        // Level 3
        gridStatic: [
            [2, 1, 1, 1, 1, 2, 2, 2, 2],
            [1, 1, 0, 0, 1, 2, 2, 2, 2],
            [1, 0, 0, 0, 1, 2, 2, 2, 2],
            [1, 1, 0, 0, 1, 1, 2, 2, 2],
            [1, 1, 0, 0, 0, 1, 2, 2, 2],
            [1, 3, 0, 0, 0, 1, 2, 2, 2],
            [1, 3, 3, 3, 3, 1, 2, 2, 2],
            [1, 1, 1, 1, 1, 1, 2, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 5, 4, 0, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 4, 0, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 4, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "down",
            "right",
            "down",
            "right",
            "down",
            "down",
            "left",
            "left",
            "right",
            "right",
            "up",
            "up",
            "left",
            "down",
            "left",
            "down",
            "right",
            "up",
            "up",
            "up",
            "left",
            "down",
            "down",
            "up",
            "up",
            "up",
            "up",
            "right",
            "down",
            "down",
            "down",
            "down"
        ]
    },
    {
        // Level 4
        gridStatic: [
            [2, 1, 1, 1, 1, 2, 2, 2, 2],
            [2, 1, 0, 0, 1, 1, 1, 2, 2],
            [2, 1, 0, 0, 0, 0, 1, 2, 2],
            [1, 1, 1, 0, 1, 0, 1, 1, 2],
            [1, 3, 1, 0, 1, 0, 0, 1, 2],
            [1, 3, 0, 0, 0, 1, 0, 1, 2],
            [1, 3, 0, 0, 0, 0, 0, 1, 2],
            [1, 1, 1, 1, 1, 1, 1, 1, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 5, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 4, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 4, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "right",
            "down",
            "right",
            "right",
            "down",
            "down",
            "right",
            "down",
            "down",
            "left",
            "left",
            "up",
            "left",
            "left",
            "down",
            "left",
            "up",
            "right",
            "right",
            "right",
            "down",
            "left",
            "left",
            "right",
            "right",
            "right",
            "right",
            "up",
            "up",
            "left",
            "up",
            "up",
            "left",
            "left",
            "down",
            "down",
            "up",
            "up",
            "right",
            "right",
            "down",
            "down",
            "right",
            "down",
            "down",
            "left",
            "left",
            "up",
            "left",
            "left"
        ]
    },
    {
        // Level 5
        gridStatic: [
            [2, 2, 1, 1, 1, 1, 1, 1, 2],
            [2, 2, 1, 0, 0, 0, 0, 1, 2],
            [1, 1, 1, 0, 0, 0, 0, 1, 2],
            [1, 0, 0, 0, 3, 3, 0, 1, 2],
            [1, 0, 0, 3, 3, 3, 1, 1, 2],
            [1, 1, 1, 1, 0, 0, 1, 2, 2],
            [2, 2, 2, 1, 1, 1, 1, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 4, 4, 4, 0, 0, 0],
            [0, 5, 0, 4, 0, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "down",
            "right",
            "right",
            "right",
            "up",
            "right",
            "right",
            "up",
            "up",
            "left",
            "left",
            "down",
            "down",
            "left",
            "down",
            "left",
            "left",
            "up",
            "right",
            "right",
            "right",
            "up",
            "up",
            "right",
            "right",
            "down",
            "left",
            "up",
            "left",
            "down",
            "up",
            "left",
            "down",
            "down"
        ]
    },
    {
        // Level 6
        gridStatic: [
            [2, 2, 1, 1, 1, 1, 1, 2, 2],
            [1, 1, 1, 0, 0, 0, 1, 2, 2],
            [1, 0, 0, 0, 3, 0, 1, 1, 2],
            [1, 0, 0, 3, 0, 3, 0, 1, 2],
            [1, 1, 1, 0, 3, 0, 0, 1, 2],
            [2, 2, 1, 0, 0, 0, 1, 1, 2],
            [2, 2, 1, 1, 1, 1, 1, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 5, 0, 0, 0],
            [0, 0, 0, 4, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 4, 0, 0, 0, 0],
            [0, 0, 0, 0, 4, 4, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "down",
            "left",
            "left",
            "down",
            "left",
            "left",
            "up",
            "right",
            "right",
            "down",
            "down",
            "down",
            "right",
            "right",
            "up",
            "up",
            "left",
            "left",
            "up",
            "left",
            "left",
            "down",
            "right",
            "up",
            "right",
            "up",
            "right",
            "right",
            "down"
        ]
    },
    {
        // Level 7
        gridStatic: [
            [2, 2, 1, 1, 1, 1, 2, 2, 2],
            [2, 2, 1, 3, 3, 1, 2, 2, 2],
            [2, 1, 1, 0, 3, 1, 1, 2, 2],
            [2, 1, 0, 0, 0, 3, 1, 2, 2],
            [1, 1, 0, 0, 0, 0, 1, 1, 2],
            [1, 0, 0, 1, 0, 0, 0, 1, 2],
            [1, 0, 0, 0, 0, 0, 0, 1, 2],
            [1, 1, 1, 1, 1, 1, 1, 1, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 4, 0, 0, 0, 0],
            [0, 0, 0, 4, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 4, 4, 0, 0, 0],
            [0, 0, 0, 5, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            'left',
            'up',
            'up',
            'right',
            'right',
            'up',
            'up',
            'down',
            'down',
            'left',
            'left',
            'down',
            'down',
            'right',
            'right',
            'up',
            'up',
            'down',
            'down',
            'right',
            'right',
            'up',
            'left',
            'down',
            'left',
            'left',
            'left',
            'up',
            'up',
            'right',
            'right',
            'up',
            'right',
            'down',
            'left',
            'left',
            'left',
            'down',
            'down',
            'right',
            'right',
            'up',
            'up',
            'right',
            'up',
            'left',
            'down',
            'down',
            'down',
            'right',
            'up',
            'up',
            'left',
            'left',
            'up',
            'up'
        ]
    },
    {
        // Level 8
        gridStatic: [
            [1, 1, 1, 1, 1, 1, 1, 1, 2],
            [1, 0, 0, 1, 0, 0, 0, 1, 2],
            [1, 0, 0, 3, 3, 0, 0, 1, 2],
            [1, 0, 0, 3, 3, 0, 1, 1, 2],
            [1, 0, 0, 3, 3, 0, 0, 1, 2],
            [1, 0, 0, 1, 0, 0, 0, 1, 2],
            [1, 1, 1, 1, 1, 1, 1, 1, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 4, 0, 0, 0],
            [0, 5, 4, 0, 4, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 4, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "up",
            "right",
            "left",
            "down",
            "down",
            "right",
            "up",
            "right",
            "right",
            "down",
            "left",
            "right",
            "down",
            "right",
            "right",
            "up",
            "left",
            "left",
            "up",
            "up",
            "up",
            "right",
            "right",
            "down",
            "left",
            "down",
            "left",
            "down",
            "down",
            "right",
            "right",
            "up",
            "left",
            "up",
            "left",
            "left",
            "left",
            "left",
            "up",
            "up",
            "right",
            "down",
            "left",
            "down",
            "right",
            "right",
            "left",
            "left",
            "down",
            "down",
            "right",
            "up",
            "left",
            "up",
            "right"
        ]
    },
    {
        // Level 9
        gridStatic: [
            [1, 1, 1, 1, 1, 1, 2, 2, 2],
            [1, 0, 0, 0, 0, 1, 2, 2, 2],
            [1, 0, 0, 0, 0, 1, 1, 2, 2],
            [1, 0, 0, 1, 3, 3, 1, 1, 1],
            [1, 1, 0, 0, 3, 3, 0, 0, 1],
            [2, 1, 0, 0, 0, 0, 0, 0, 1],
            [2, 1, 1, 1, 1, 1, 1, 1, 1],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 4, 4, 4, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 4, 0, 0],
            [0, 0, 0, 5, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "up",
            "left",
            "up",
            "left",
            "up",
            "up",
            "right",
            "right",
            "right",
            "down",
            "down",
            "right",
            "down",
            "left",
            "up",
            "up",
            "up",
            "left",
            "left",
            "down",
            "right",
            "up",
            "right",
            "down",
            "down",
            "right",
            "down",
            "down",
            "right",
            "right",
            "up",
            "left",
            "down",
            "left",
            "up",
            "down",
            "left",
            "up",
            "down",
            "left",
            "left",
            "up",
            "right",
            "right",
            "left",
            "left",
            "up",
            "left",
            "up",
            "right",
            "up",
            "right",
            "right",
            "down",
            "down",
            "up",
            "up",
            "left",
            "left",
            "down",
            "right",
            "up",
            "right",
            "down"
        ]
    },
    {
        // Level 10
        gridStatic: [
            [1, 1, 1, 1, 1, 1, 1, 2, 2],
            [1, 3, 3, 0, 3, 3, 1, 2, 2],
            [1, 3, 3, 1, 3, 3, 1, 2, 2],
            [1, 0, 0, 0, 0, 0, 1, 2, 2],
            [1, 0, 0, 0, 0, 0, 1, 2, 2],
            [1, 0, 0, 0, 0, 0, 1, 2, 2],
            [1, 0, 0, 1, 0, 0, 1, 2, 2],
            [1, 1, 1, 1, 1, 1, 1, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 4, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 4, 4, 4, 0, 0, 0, 0],
            [0, 0, 0, 4, 0, 0, 0, 0, 0],
            [0, 0, 4, 4, 4, 0, 0, 0, 0],
            [0, 0, 0, 0, 5, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "right",
            "up",
            "up",
            "left",
            "up",
            "right",
            "up",
            "up",
            "left",
            "left",
            "left",
            "down",
            "left",
            "down",
            "down",
            "right",
            "up",
            "up",
            "down",
            "down",
            "left",
            "down",
            "down",
            "right",
            "up",
            "up",
            "up",
            "right",
            "right",
            "up",
            "down",
            "down",
            "right",
            "up",
            "up",
            "down",
            "down",
            "down",
            "down",
            "left",
            "up",
            "up",
            "up",
            "down",
            "down",
            "left",
            "up",
            "down",
            "left",
            "down",
            "left",
            "up",
            "up",
            "up",
            "right",
            "right",
            "right",
            "down",
            "right",
            "up"
        ]
    },
    {
        // Level 11
        gridStatic: [
            [2, 1, 1, 1, 1, 1, 2, 2, 2],
            [2, 1, 0, 0, 0, 1, 1, 1, 2],
            [1, 1, 0, 1, 0, 0, 0, 1, 2],
            [1, 0, 3, 3, 0, 3, 0, 1, 2],
            [1, 0, 0, 0, 0, 0, 1, 1, 2],
            [1, 1, 1, 0, 1, 3, 1, 2, 2],
            [2, 2, 1, 0, 0, 0, 1, 2, 2],
            [2, 2, 1, 1, 1, 1, 1, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 5, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 4, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 4, 4, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "right",
            "down",
            "right",
            "down",
            "down",
            "down",
            "down",
            "left",
            "left",
            "up",
            "up",
            "left",
            "up",
            "down",
            "right",
            "down",
            "down",
            "right",
            "right",
            "up",
            "up",
            "left",
            "right",
            "up",
            "up",
            "left",
            "down",
            "left",
            "down",
            "left",
            "left",
            "up",
            "right",
            "right",
            "right",
            "up",
            "right",
            "right",
            "down",
            "left",
            "down",
            "left",
            "left",
            "up",
            "right",
            "down",
            "right",
            "up",
            "left",
            "left",
            "left",
            "left",
            "down",
            "right",
            "right",
            "up",
            "right",
            "right",
            "down",
            "down",
            "down",
            "left",
            "left",
            "up",
            "up",
            "right",
            "up",
            "up",
            "up",
            "left",
            "left",
            "down",
            "down",
            "left",
            "down",
            "right",
            "right",
            "left",
            "up",
            "up",
            "up",
            "right",
            "right",
            "down",
            "down",
            "right",
            "right",
            "up",
            "left",
            "down",
            "left",
            "left",
            "down",
            "down",
            "down",
            "right",
            "right",
            "up",
            "up",
            "down",
            "down",
            "left",
            "left",
            "up",
            "up",
            "right",
            "left",
            "left",
            "left",
            "up",
            "right",
            "up",
            "up",
            "right",
            "right",
            "down",
            "down",
            "left",
            "down",
            "left",
            "up",
            "right",
            "right",
            "up",
            "right",
            "right",
            "down",
            "left",
            "left",
            "left",
            "down",
            "down",
            "down",
            "right",
            "right",
            "up",
            "up",
            "down",
            "down",
            "left",
            "left",
            "up",
            "up",
            "right",
            "up",
            "up",
            "right",
            "right",
            "down",
            "left",
            "down",
            "left",
            "left",
            "up",
            "right",
            "down",
            "left",
            "left",
            "left",
            "up",
            "right",
            "down",
            "right",
            "right",
            "up",
            "up",
            "up",
            "left",
            "left",
            "down"
        ]
    },
    {
        // Level 12
        gridStatic: [
            [1, 1, 1, 1, 1, 1, 2, 2, 2],
            [1, 0, 0, 0, 0, 1, 2, 2, 2],
            [1, 0, 0, 0, 0, 1, 2, 2, 2],
            [1, 1, 3, 0, 0, 1, 2, 2, 2],
            [1, 0, 3, 0, 1, 1, 2, 2, 2],
            [1, 0, 3, 0, 1, 2, 2, 2, 2],
            [1, 0, 3, 0, 1, 2, 2, 2, 2],
            [1, 0, 3, 0, 1, 2, 2, 2, 2],
            [1, 1, 1, 1, 1, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 4, 0, 5, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "down",
            "left",
            "down",
            "down",
            "down",
            "down",
            "left",
            "left",
            "up",
            "up",
            "up",
            "right",
            "left",
            "down",
            "down",
            "down",
            "right",
            "right",
            "up",
            "up",
            "up",
            "left",
            "left",
            "down",
            "right",
            "down",
            "up",
            "up",
            "right",
            "up",
            "right",
            "up",
            "up",
            "left",
            "down",
            "up",
            "left",
            "left",
            "down",
            "right",
            "down",
            "down",
            "up",
            "up",
            "up",
            "right",
            "right",
            "down",
            "left",
            "right",
            "down",
            "left",
            "down",
            "left",
            "left",
            "down",
            "down",
            "right",
            "right",
            "up",
            "up",
            "left",
            "down",
            "up",
            "right",
            "up",
            "right",
            "up",
            "up",
            "left",
            "down",
            "up",
            "left",
            "left",
            "down",
            "right",
            "down",
            "down",
            "up",
            "up",
            "up",
            "right",
            "right",
            "down",
            "left",
            "up",
            "left",
            "down",
            "down",
            "up",
            "right",
            "right",
            "down",
            "left"
        ]
    },
    {
        // Level 13
        gridStatic: [
            [2, 2, 1, 1, 1, 1, 2, 2, 2],
            [2, 2, 1, 0, 0, 1, 2, 2, 2],
            [1, 1, 1, 0, 0, 1, 1, 2, 2],
            [1, 0, 0, 3, 0, 0, 1, 2, 2],
            [1, 0, 0, 3, 0, 0, 1, 2, 2],
            [1, 0, 0, 3, 0, 1, 1, 2, 2],
            [1, 1, 1, 3, 0, 1, 2, 2, 2],
            [2, 2, 1, 3, 1, 1, 2, 2, 2],
            [2, 2, 1, 1, 1, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 4, 0, 0, 0, 0, 0],
            [0, 0, 0, 4, 0, 5, 0, 0, 0],
            [0, 0, 0, 4, 0, 0, 0, 0, 0],
            [0, 0, 0, 4, 0, 0, 0, 0, 0],
            [0, 0, 0, 4, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "down",
            "left",
            "down",
            "left",
            "down",
            "up",
            "right",
            "up",
            "up",
            "left",
            "down",
            "left",
            "left",
            "up",
            "right",
            "right",
            "down",
            "right",
            "down",
            "down",
            "left",
            "up",
            "right",
            "up",
            "left",
            "up",
            "left",
            "left",
            "down",
            "down",
            "right",
            "left",
            "up",
            "up",
            "right",
            "right",
            "down",
            "down",
            "up",
            "right",
            "right",
            "up",
            "left",
            "left",
            "right",
            "up",
            "up",
            "left",
            "down",
            "down",
            "right",
            "down",
            "down",
            "left",
            "left",
            "left",
            "up",
            "up",
            "right",
            "down",
            "left",
            "down",
            "right"
        ]
    },
    {
        // Level 14
        gridStatic: [
            [1, 1, 1, 1, 1, 2, 2, 2, 2],
            [1, 0, 0, 0, 1, 1, 1, 1, 1],
            [1, 0, 1, 0, 1, 0, 0, 0, 1],
            [1, 0, 0, 0, 0, 0, 0, 0, 1],
            [1, 3, 3, 1, 0, 1, 0, 1, 1],
            [1, 3, 0, 0, 0, 0, 0, 1, 2],
            [1, 3, 3, 0, 0, 1, 1, 1, 2],
            [1, 1, 1, 1, 1, 1, 2, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 4, 0, 0, 0, 4, 0, 0],
            [0, 0, 0, 0, 4, 0, 4, 0, 0],
            [0, 0, 5, 4, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "down",
            "right",
            "right",
            "up",
            "left",
            "down",
            "left",
            "up",
            "left",
            "up",
            "up",
            "up",
            "up",
            "right",
            "right",
            "down",
            "down",
            "left",
            "down",
            "down",
            "left",
            "down",
            "right",
            "up",
            "up",
            "up",
            "right",
            "right",
            "right",
            "up",
            "right",
            "right",
            "down",
            "left",
            "left",
            "left",
            "left",
            "up",
            "up",
            "left",
            "left",
            "down",
            "down",
            "down",
            "right",
            "down",
            "right",
            "right",
            "right",
            "right",
            "up",
            "down",
            "left",
            "left",
            "left",
            "left",
            "up",
            "left",
            "up",
            "up",
            "up",
            "right",
            "right",
            "down",
            "down",
            "right",
            "down",
            "up",
            "right",
            "up",
            "right",
            "right",
            "down",
            "left",
            "down",
            "down",
            "left",
            "left",
            "up",
            "up",
            "right",
            "up",
            "right",
            "down",
            "left",
            "left",
            "left",
            "up",
            "up",
            "left",
            "left",
            "down",
            "down",
            "down",
            "right",
            "down",
            "down",
            "left",
            "up",
            "up",
            "up",
            "right",
            "right",
            "right",
            "down",
            "down",
            "left",
            "right",
            "up",
            "up",
            "left",
            "left",
            "down",
            "left",
            "down",
            "down",
            "right",
            "up",
            "right",
            "right",
            "up",
            "up",
            "right",
            "up",
            "right",
            "right",
            "down",
            "left",
            "left",
            "left",
            "left",
            "up",
            "up",
            "left",
            "left",
            "down",
            "down",
            "down",
            "down",
            "right",
            "right",
            "right",
            "down",
            "left",
            "up",
            "right",
            "right",
            "right",
            "up",
            "down",
            "left",
            "left",
            "up",
            "up",
            "left",
            "left",
            "right",
            "up",
            "up",
            "left",
            "left",
            "down",
            "down",
            "down",
            "up",
            "right",
            "right",
            "right",
            "right",
            "up",
            "right",
            "right",
            "down",
            "left",
            "left",
            "left",
            "left",
            "left",
            "right",
            "up",
            "up",
            "left",
            "left",
            "down",
            "down"
        ]
    },
    {
        // Level 15
        gridStatic: [
            [2, 1, 1, 1, 1, 1, 1, 2, 2],
            [2, 1, 0, 0, 0, 0, 1, 1, 2],
            [1, 1, 3, 1, 1, 0, 0, 1, 2],
            [1, 0, 3, 3, 0, 0, 0, 1, 2],
            [1, 0, 0, 1, 0, 0, 0, 1, 2],
            [1, 0, 0, 0, 0, 1, 1, 1, 2],
            [1, 1, 1, 1, 1, 1, 2, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
            [2, 2, 2, 2, 2, 2, 2, 2, 2],
        ],
        gridDynamic: [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 4, 0, 0, 0],
            [0, 0, 0, 0, 4, 0, 0, 0, 0],
            [0, 0, 0, 0, 4, 0, 0, 0, 0],
            [0, 0, 0, 5, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        solutionMoves: [
            "left",
            "up",
            "up",
            "up",
            "up",
            "right",
            "right",
            "right",
            "down",
            "down",
            "left",
            "left",
            "right",
            "right",
            "up",
            "up",
            "left",
            "left",
            "left",
            "down",
            "down",
            "left",
            "down",
            "down",
            "right",
            "right",
            "right",
            "up",
            "down",
            "left",
            "left",
            "left",
            "up",
            "up",
            "right",
            "right",
            "right",
            "left",
            "left",
            "up",
            "up",
            "right",
            "right",
            "right",
            "down",
            "right",
            "down",
            "down",
            "left",
            "up",
            "left",
            "left",
            "left",
            "left",
            "down",
            "down",
            "right",
            "right",
            "right",
            "up",
            "right",
            "up",
            "left",
            "down",
            "down",
            "left",
            "left",
            "left",
            "up",
            "up",
            "right",
            "up",
            "up",
            "right",
            "right",
            "right",
            "down",
            "right",
            "down",
            "down",
            "left",
            "left",
            "down",
            "left",
            "left",
            "up",
            "up",
            "down",
            "down",
            "right",
            "right",
            "up",
            "up",
            "left",
            "right",
            "down",
            "right",
            "right",
            "up",
            "left",
            "left"
        ]
    },
]